### ISSUE TITLE
App fails to run

### ISSUE THREAD

**Issue by plorch** [ConservationInternational/Wild.ID#1]
This app launches but then hangs and fails to respond on the Mac (must be force quit).  This is true whether you use .app or double click the .jar.

On Windows 10, the app gives an error on launch (cannot find JVM.dll) and fails to launch.  However, you can launch the app by double clicking the .jar file, and it works fine.

**Comment by vnandigam** [comment]
Can you please try with the latest version (v.0.9.3) which includes several bug fixes and see if you still have the problem?

**Comment by eric-fegraus** [comment]
This issue is resolved. Please let us know if you have further problems

**Comment by ghost** [comment]
Hey everyone, 

I am still experiencing the same issue. I am trying to launch the app on Windows 10, however get an error, follow by the message 'failed to launch JVM'. Any suggestions on how this can be resolved? The .jar file also does not run. 

Cheers,
